const produxt =[
    {
        name:"t-shirt",
        img:"/Assets/img/products/f1.jpg",
        brand:"chine",
        _id:"44",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f2.jpg",
        brand:"chine",
        _id:"33",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f3.jpg",
        brand:"chine",
        _id:"33",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/n1.jpg",
        brand:"chine",
        _id:"33",
        price:"129$"
    },

    {
        name:"t-shirt",
        img:"/Assets/img/products/f3.jpg",
        brand:"chine",
        _id:"22",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f4.jpg",
        brand:"chine",
        _id:"11",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/n4.jpg",
        brand:"chine",
        _id:"11",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f5.jpg",
        brand:"chine",
        _id:"10",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f1.jpg",
        brand:"chine",
        _id:"9",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/n1.jpg",
        brand:"chine",
        _id:"9",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f6.jpg",
        brand:"chine",
        _id:"8",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f7.jpg",
        brand:"chine",
        _id:"7",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/n7.jpg",
        brand:"chine",
        _id:"7",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f8.jpg",
        brand:"chine",
        _id:"6",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/n8.jpg",
        brand:"chine",
        _id:"6",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f3.jpg",
        brand:"chine",
        _id:"5",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f2.jpg",
        brand:"chine",
        _id:"4",
        price:"114$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f4.jpg",
        brand:"chine",
        _id:"3",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f7.jpg",
        brand:"chine",
        _id:"2",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f1.jpg",
        brand:"chine",
        _id:"123",
        price:"129$"
    },
    {
        name:"t-shirt",
        img:"/Assets/img/products/f5.jpg",
        brand:"chine",
        _id:"1",
        price:"129$"
    },
  ];
  export default produxt;